name = "unchained"
version = "0.0.1"

description = "A framework for developing applications powered by large language models (LLMs) in Gleam"
licences = ["MIT"]
repository = { type = "github", user = "lostbean", repo = "unchained" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
handles = ">= 4.0.1 and < 5.0.0"
gleam_httpc = ">= 3.0.0 and < 4.0.0"
gleam_otp = ">= 0.14.1 and < 1.0.0"
gleam_erlang = ">= 0.30.0 and < 1.0.0"
json_blueprint = ">= 1.5.0 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
