name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    name: Check Nix
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Magic cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@v7
        with:
          fail-mode: true

      - name: Nix Check
        run: |
          nix flake check

      - run: nix develop --command gleam test
